name: Build and Release APP Demo

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: main

jobs:
  build:
    name: Build Mode
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ toJson(github) }}"

  deployTest:
    name: Deploy test
    runs-on: ubuntu-latest
    needs: build
    steps:
    - run: echo "${{ toJson(github) }}"

  deployProd:
    name: Deploy Prod
    runs-on: ubuntu-latest
    needs: deployTest
    environment: production
    steps:
    - run: echo "${{ toJson(github) }}"
