name: Release APP Demo

on:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [main]
    types: 
      - completed

jobs:
  build:
    name: Release Mode
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ toJson(github) }}"
